version: "2.1"

services:
  redis:
    image: redis:5.0-rc5
    volumes:
      - ./volumes/redis:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

  zookeeper:
    image: wurstmeister/zookeeper:latest
    volumes:
      - ./volumes/zookeeper:/opt/zookeeper-3.4.9/data
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    ports:
      - "9092:9092"
    environment:
      #- KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      #- KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT
      #- KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_LOG_DIRS=/kafka/logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/kafka:/kafka
    restart: unless-stopped
